/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.sanpham;
import model.SanphamCT;
import model.Hoadon;
import controller.DAOspCT;
import controller.DAOsp;
import controller.DAOhd;
import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.lang.UnsupportedOperationException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import controller.ServerConnection;

/**
 *
 * @author ADMIN
 */
public class Capnhatdonhang extends javax.swing.JFrame {

    /**
     * Creates new form user
     */
    private List<Hoadon> hoadon;
    private List<sanpham> Sanpham;
    private List<SanphamCT> sanphamct;
    private List<sanpham> anhsp;
    private DefaultTableModel ModelHD;
    private static DefaultTableModel ModelSP;
    private DefaultTableModel ModelSPCT;
    int selectedIndex;
    private sanpham currentsp;
    private Iterable<SanphamCT> sanphamCT;
    private DAOsp dao;
    public Capnhatdonhang() {
        initComponents();
        ModelHD=(DefaultTableModel) TableHoadon.getModel();
        ModelSP=(DefaultTableModel) TableSP.getModel();
        ModelSPCT=(DefaultTableModel) TableSPCT.getModel();
        dao = new DAOsp(); 
        showTableHD();
        showTableSP();
        showTableSPCT();
        Tong();
        
        menubar.setVisible(false);
        jScrollPane2.setVisible(false);
        jScrollPane3.setVisible(false);
        jLabel12.setVisible(false);
        tong.setVisible(false);
        jPanel3.setVisible(false);
        btnupdateslg.setVisible(false);
        
        
        ModelHD.addTableModelListener(new TableModelListener() {
        @Override
            public void tableChanged(TableModelEvent e) {
                Tong();
            }
        });
    }
    

    int width = 205;
    int height = 530;

    void openMenuBar() {
        new Thread(() -> {
            for (int currentWidth = 0; currentWidth <= width; currentWidth++) {
                try {
                    Thread.sleep(2);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                pnMenu.setSize(currentWidth, height);
            }
        }).start();
    }

    void closeMenuBar() {
        new Thread(() -> {
            for (int currentWidth = width; currentWidth >= 0; currentWidth--) {
                try {
                    Thread.sleep(2);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                pnMenu.setSize(currentWidth, height);
            }
        }).start();
    }

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSP = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableSPCT = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableHoadon = new javax.swing.JTable();
        close = new javax.swing.JLabel();
        menubar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTKH = new javax.swing.JTextField();
        txtSĐT = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        txtDateOrder = new javax.swing.JTextField();
        jDate = new com.toedter.calendar.JDateChooser();
        Chon = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtMasp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTensp = new javax.swing.JTextField();
        ComboxKind = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSolg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tong = new javax.swing.JLabel();
        btnupdateslg = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        addstt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        addmsp = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        addtsp = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        addl = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        addsl = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        addg = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        addha = new javax.swing.JTextField();
        pnMenu = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        banghd = new javax.swing.JButton();
        bangctsp = new javax.swing.JButton();
        btnaddsp = new javax.swing.JButton();
        btnxoasp = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 178, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        TableSP.setAutoCreateRowSorter(true);
        TableSP.setBackground(new java.awt.Color(22, 36, 48));
        TableSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TableSP.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        TableSP.setForeground(new java.awt.Color(204, 255, 255));
        TableSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Loại", "Số lượng kho", "Giá", "Hình ảnh"
            }
        ));
        TableSP.setGridColor(new java.awt.Color(153, 153, 153));
        TableSP.setSelectionBackground(new java.awt.Color(255, 153, 0));
        TableSP.setSelectionForeground(new java.awt.Color(0, 0, 51));
        TableSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableSP);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 470, 200));

        TableSPCT.setBackground(new java.awt.Color(22, 36, 48));
        TableSPCT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TableSPCT.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        TableSPCT.setForeground(new java.awt.Color(204, 255, 255));
        TableSPCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Số lượng", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableSPCT.setSelectionBackground(new java.awt.Color(255, 153, 0));
        TableSPCT.setSelectionForeground(new java.awt.Color(0, 0, 51));
        TableSPCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSPCTMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableSPCT);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 470, 250));

        TableHoadon.setBackground(new java.awt.Color(22, 36, 48));
        TableHoadon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TableHoadon.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        TableHoadon.setForeground(new java.awt.Color(204, 255, 255));
        TableHoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên khách hàng", "SĐT", "Địa chỉ", "Ngày đặt", "Thành tiền (VNĐ)"
            }
        ));
        TableHoadon.setSelectionBackground(new java.awt.Color(255, 153, 0));
        TableHoadon.setSelectionForeground(new java.awt.Color(0, 0, 51));
        TableHoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableHoadonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableHoadon);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 600, 330));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmages/icons8_delete_26px.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.setPreferredSize(new java.awt.Dimension(80, 48));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 40, 30));

        menubar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmages/menu.png"))); // NOI18N
        menubar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menubar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menubarMouseClicked(evt);
            }
        });
        getContentPane().add(menubar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(22, 36, 48));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên khách hàng:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Số điện thoại: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Địa chỉ:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 50, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ngày đặt:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 30));

        txtTKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTKHActionPerformed(evt);
            }
        });
        jPanel1.add(txtTKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 140, 30));

        txtSĐT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSĐTActionPerformed(evt);
            }
        });
        jPanel1.add(txtSĐT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 140, 30));

        txtDiachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiachiActionPerformed(evt);
            }
        });
        jPanel1.add(txtDiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 140, 30));

        txtDateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOrderActionPerformed(evt);
            }
        });
        jPanel1.add(txtDateOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 110, 30));

        jDate.setBackground(new java.awt.Color(255, 255, 255));
        jDate.setDateFormatString("dd-MM-yyyy");
        jPanel1.add(jDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 35, 30));
        jDate.getAccessibleContext().setAccessibleName("");

        Chon.setBackground(new java.awt.Color(204, 204, 204));
        Chon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Chon.setText("Chọn ngày");
        Chon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chon.setBorderPainted(false);
        Chon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChonActionPerformed(evt);
            }
        });
        jPanel1.add(Chon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 100, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mã sản phẩm:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 30));
        jPanel1.add(txtMasp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 140, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tên sản phẩm:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));
        jPanel1.add(txtTensp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 140, 30));

        ComboxKind.setEditable(true);
        ComboxKind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T-shirt", "Hoodie", "Long Sleeve", "Sweater", "Short", "Jean" }));
        ComboxKind.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboxKind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboxKindActionPerformed(evt);
            }
        });
        jPanel1.add(ComboxKind, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 140, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Loại:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Số lượng:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        txtSolg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSolgActionPerformed(evt);
            }
        });
        jPanel1.add(txtSolg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 140, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Giá:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));
        jPanel1.add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 140, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ĐẶT HÀNG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 300, 530));

        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 60, 100, 150));

        tong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tong.setText("Tổng doanh thu: ");
        getContentPane().add(tong, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 580, 260, 20));

        btnupdateslg.setBackground(new java.awt.Color(0, 153, 51));
        btnupdateslg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnupdateslg.setForeground(new java.awt.Color(255, 255, 255));
        btnupdateslg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmages/icons8_add_25px_1.png"))); // NOI18N
        btnupdateslg.setText("Cập nhật số lượng");
        btnupdateslg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnupdateslg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnupdateslg.setOpaque(true);
        btnupdateslg.setPreferredSize(new java.awt.Dimension(170, 47));
        btnupdateslg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateslgActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdateslg, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        jPanel3.setBackground(new java.awt.Color(22, 36, 48));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("THÊM SẢN PHẨM MỚI");
        jPanel3.add(jLabel13);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("STT:                 ");
        jPanel3.add(jLabel20);

        addstt.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel3.add(addstt);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Mã sản phẩm: ");
        jPanel3.add(jLabel14);

        addmsp.setPreferredSize(new java.awt.Dimension(120, 25));
        addmsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmspActionPerformed(evt);
            }
        });
        jPanel3.add(addmsp);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tên sản phẩm:");
        jPanel3.add(jLabel15);

        addtsp.setPreferredSize(new java.awt.Dimension(120, 25));
        addtsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtspActionPerformed(evt);
            }
        });
        jPanel3.add(addtsp);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Loại:                 ");
        jPanel3.add(jLabel16);

        addl.setPreferredSize(new java.awt.Dimension(120, 25));
        addl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addlActionPerformed(evt);
            }
        });
        jPanel3.add(addl);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Số lượng:        ");
        jPanel3.add(jLabel17);

        addsl.setPreferredSize(new java.awt.Dimension(120, 25));
        addsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addslActionPerformed(evt);
            }
        });
        jPanel3.add(addsl);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Giá:                  ");
        jPanel3.add(jLabel18);

        addg.setPreferredSize(new java.awt.Dimension(120, 25));
        addg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addgActionPerformed(evt);
            }
        });
        jPanel3.add(addg);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Hình ảnh:        ");
        jPanel3.add(jLabel19);

        addha.setPreferredSize(new java.awt.Dimension(120, 25));
        addha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addhaActionPerformed(evt);
            }
        });
        jPanel3.add(addha);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 240, 260));

        pnMenu.setBackground(new java.awt.Color(22, 36, 48));
        pnMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnMenu.setForeground(new java.awt.Color(255, 255, 255));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmages/logo (2).png"))); // NOI18N
        jLabel23.setText("jLabel23");
        jLabel23.setPreferredSize(new java.awt.Dimension(107, 100));
        pnMenu.add(jLabel23);

        banghd.setBackground(new java.awt.Color(0, 204, 204));
        banghd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        banghd.setText("Bảng hoá đơn");
        banghd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        banghd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        banghd.setPreferredSize(new java.awt.Dimension(170, 47));
        banghd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banghdMouseClicked(evt);
            }
        });
        banghd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banghdActionPerformed(evt);
            }
        });
        pnMenu.add(banghd);
        banghd.getAccessibleContext().setAccessibleDescription("");

        bangctsp.setBackground(new java.awt.Color(0, 204, 204));
        bangctsp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bangctsp.setText("Bảng đơn hàng chi tiết");
        bangctsp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bangctsp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bangctsp.setOpaque(true);
        bangctsp.setPreferredSize(new java.awt.Dimension(170, 47));
        bangctsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangctspMouseClicked(evt);
            }
        });
        bangctsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangctspActionPerformed(evt);
            }
        });
        pnMenu.add(bangctsp);

        btnaddsp.setBackground(new java.awt.Color(0, 204, 204));
        btnaddsp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnaddsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmages/icons8_add_to_clipboard_25px.png"))); // NOI18N
        btnaddsp.setText("Thêm sản phẩm");
        btnaddsp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnaddsp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnaddsp.setMaximumSize(new java.awt.Dimension(86, 20));
        btnaddsp.setMinimumSize(new java.awt.Dimension(86, 20));
        btnaddsp.setOpaque(true);
        btnaddsp.setPreferredSize(new java.awt.Dimension(170, 47));
        btnaddsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddspMouseClicked(evt);
            }
        });
        btnaddsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddspActionPerformed(evt);
            }
        });
        pnMenu.add(btnaddsp);

        btnxoasp.setBackground(new java.awt.Color(0, 204, 204));
        btnxoasp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnxoasp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmages/icons8_delete_bin_30px.png"))); // NOI18N
        btnxoasp.setText("Xoá sản phẩm");
        btnxoasp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnxoasp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnxoasp.setOpaque(true);
        btnxoasp.setPreferredSize(new java.awt.Dimension(170, 47));
        btnxoasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaspActionPerformed(evt);
            }
        });
        pnMenu.add(btnxoasp);

        btnAdd.setBackground(new java.awt.Color(0, 204, 204));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmages/icons8_add_25px_1.png"))); // NOI18N
        btnAdd.setText("Thêm đơn hàng mới");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setOpaque(true);
        btnAdd.setPreferredSize(new java.awt.Dimension(170, 47));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        pnMenu.add(btnAdd);

        btnDelete.setBackground(new java.awt.Color(0, 204, 204));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmages/icons8_delete_25px_2.png"))); // NOI18N
        btnDelete.setText("Xoá hoá đơn");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setOpaque(true);
        btnDelete.setPreferredSize(new java.awt.Dimension(170, 47));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnMenu.add(btnDelete);

        btnsave.setBackground(new java.awt.Color(0, 204, 204));
        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmages/icons8_save_all_25px.png"))); // NOI18N
        btnsave.setText("Đặt hàng");
        btnsave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsave.setOpaque(true);
        btnsave.setPreferredSize(new java.awt.Dimension(170, 47));
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        pnMenu.add(btnsave);

        jButton1.setBackground(new java.awt.Color(255, 102, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ĐĂNG XUẤT");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(130, 45));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnMenu.add(jButton1);

        getContentPane().add(pnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 530));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmages/bia.jpg"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        txtTKH.setText("");
        txtDiachi.setText("");
        txtSĐT.setText("");
        txtDateOrder.setText("");
        txtMasp.setText("");
        txtTensp.setText("");
        txtSolg.setText("");
        txtGia.setText("");
        ComboxKind.setSelectedIndex(0);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnaddspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddspActionPerformed
//        String Masp="";
//        int soluong=0;
//        int gia=0;
//        Masp=txtMasp.getText();
//        soluong=Integer.parseInt(txtSolg.getText());
//        gia=Integer.parseInt(txtGia.getText());
//        int Gia=soluong*gia;
//        SanphamCT sp=new SanphamCT(Masp, soluong, Gia);
//        new DAOspCT().AddSP(sp);
//        showTableSPCT();
    jPanel3.setVisible(true);
    jPanel1.setVisible(false);
    try {
        // Lấy thông tin sản phẩm từ các thành phần GUI
        int stt = Integer.parseInt(addstt.getText());
        String masp = addmsp.getText();
        String tensp = addtsp.getText();
        String loai = addl.getText();
        int soluong = Integer.parseInt(addsl.getText());
        int gia = Integer.parseInt(addg.getText());
        String hinhanh = addha.getText();
     
        addstt.setText("");
        addmsp.setText("");
        addtsp.setText("");
        addl.setText("");
        addsl.setText("");
        addg.setText("");
        addha.setText("");
        
        // Kiểm tra xem tất cả các trường đều đã được nhập
        if (masp.isEmpty() || tensp.isEmpty() || loai.isEmpty() || hinhanh.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin sản phẩm");
        } else {
            // Thêm sản phẩm mới vào cơ sở dữ liệu
            ModelSP.addRow(new Object[]{stt, masp, tensp, loai, soluong, gia, hinhanh});    
            sanpham newSP = new sanpham(stt, masp, tensp, loai, soluong, gia, hinhanh);
            dao.AddSP(newSP);

            // Hiển thị thông báo khi thêm thành công
            JOptionPane.showMessageDialog(this, "Đã thêm sản phẩm mới thành công");
            ServerConnection.sendspUpdateToServer(newSP);

            // Cập nhật bảng hiển thị
            showTableSP();
        }
    } catch (NumberFormatException ex) {
        // Xử lý nếu người dùng nhập sai định dạng số
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin sản phẩm");
    }
    }//GEN-LAST:event_btnaddspActionPerformed

    private void loadData() {
        // Khởi tạo DAO và lấy danh sách sản phẩm
        DAOsp dao = new DAOsp();
        ArrayList<sanpham> invoiceList = dao.getListSP();
        ModelSP.setRowCount(0);
  for (sanpham Sanpham : invoiceList) {
            ModelSP.addRow(new Object[]{Sanpham.getMasp(),Sanpham.getTensp(), Sanpham.getLoai(), Sanpham.getSoluong(), Sanpham.getGia(), Sanpham.getHinhAnh() });
        }
    }
    private void TableSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSPMouseClicked
        selectedIndex=TableSP.getSelectedRow();
        sanpham sp= Sanpham.get(selectedIndex);
        txtMasp.setText(sp.getMasp());
        txtTensp.setText(sp.getTensp());
        ComboxKind.setSelectedItem(sp.getLoai());
        txtGia.setText(sp.getGia()+"");
            
        int selectedIndex = TableSP.getSelectedRow();
        if (selectedIndex != -1) {
            String imageName = TableSP.getValueAt(selectedIndex, 6).toString();
            ImageIcon imageIcon = new ImageIcon(getClass().getResource(imageName));
            Image img = imageIcon.getImage();
            Image newImg = img.getScaledInstance(100, 150, java.awt.Image.SCALE_SMOOTH);
            jLabel12.setIcon(new ImageIcon(newImg));
         }
        
        jLabel12.setVisible(true);
        
    }//GEN-LAST:event_TableSPMouseClicked
       private int clickCount = 0;
       private int lastSelectedIndex = -1;
    private void TableSPCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSPCTMouseClicked
    int currentIndex = TableSPCT.getSelectedRow();
    if (currentIndex == lastSelectedIndex) {
        clickCount++;
    } else {
        clickCount = 1; // Reset số lần nhấp khi chọn hàng khác
        lastSelectedIndex = currentIndex;
    }

    if (clickCount == 2) {
        SanphamCT spct = sanphamct.get(currentIndex);
        new DAOspCT().DeleteSPCT(spct.getID());
        showTableSPCT();
        clickCount = 0; // Reset số lần nhấp sau khi xóa
        lastSelectedIndex = -1; // Reset chỉ số hàng đã chọn
    }
    }//GEN-LAST:event_TableSPCTMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        selectedIndex=TableHoadon.getSelectedRow();
        int confirmationResult=JOptionPane.showConfirmDialog(this,"Bạn có chắc muốn xoá!");
        Hoadon hd =hoadon.get(selectedIndex);
        if(confirmationResult==JOptionPane.YES_OPTION) { 
            ServerConnection.sendDeletedhdToServer(hd);
        new DAOhd().DeleteHD(hd.getMaHD());
        showTableHD();
    }
         jPanel1.setVisible(true);
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
//        jPanel1.setVisible(true);
//        String DateOrder = "";
//        int gia = 0;
//        int soluong=0;
//        String TKH = "";
//        String Diachi = "";
//        ComboxKind.setSelectedIndex(0);
//        int SĐT = 0;
//        int MaHD = 0;
//       try {
//        TKH = txtTKH.getText(); // Lấy tên khách hàng từ ô văn bản
//        Diachi = txtDiachi.getText(); // Lấy địa chỉ từ ô văn bản
//        SĐT = Integer.parseInt(txtSĐT.getText()); // Lấy số điện thoại từ ô văn bản
//        soluong=Integer.parseInt(txtSolg.getText());
//        gia=Integer.parseInt(txtGia.getText());
//        gia=soluong*gia;
//
//        DateOrder = txtDateOrder.getText();
//        Hoadon hd = new Hoadon(MaHD, TKH, SĐT, Diachi, DateOrder, gia);
//        new DAOhd().AddHD(hd);
//        showTableHD();
//        ServerConnection.sendspInfoToServer(hd);
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(this, "Đặt hàng không thành công! Vui lòng kiểm tra thông tin nhập vào.");
//            e.printStackTrace(); // You can remove this line in production, it's for debugging purposes.
//        }
//
//       String Masp="";
//        
//        Masp=txtMasp.getText();
//        soluong=Integer.parseInt(txtSolg.getText());
//        gia=Integer.parseInt(txtGia.getText());
//        int Gia=soluong*gia;
//        SanphamCT sp=new SanphamCT(Masp, soluong, Gia);
//        new DAOspCT().AddSP(sp);
//        showTableSPCT();
//
        banhang();
//        showTableSP();

    }//GEN-LAST:event_btnsaveActionPerformed

    public static int getSPQuantity(String masp) {
    for (int i = 0; i < ModelSP.getRowCount(); i++) {
        if (masp.equals(ModelSP.getValueAt(i, 1))) { 
            return (int) ModelSP.getValueAt(i, 4);  
        }
    }
    return -1;  // Return -1 or an appropriate value if not found
}

    private void banhang() {
    String masp = txtMasp.getText();
    int soLuongBan;
    try {
        soLuongBan = Integer.parseInt(txtSolg.getText());
    } catch (NumberFormatException e) {
        System.out.println("So luong ban khong hop le.");
        return;
    }

    sanpham currentsp = dao.getProductById(masp);
    if (currentsp != null) {
        int soLuongHienTai = currentsp.getSoluong();
        if (soLuongHienTai >= 0) {
            int soLuongConLai = soLuongHienTai - soLuongBan;
            if (soLuongBan > soLuongHienTai) {
                JOptionPane.showMessageDialog(rootPane, "Hàng không đủ số lượng để bán. Vui lòng nhập thêm hàng!");
                jPanel3.setVisible(true);
                jPanel1.setVisible(false);
                btnupdateslg.setVisible(true);
                
            }
            if (soLuongConLai >= 0) {
                dao.updateSPQuantity(masp, soLuongConLai);
                JOptionPane.showMessageDialog(this, "Đặt hàng thành công!");
                System.out.println("Dat hang thanh cong!");
                jPanel1.setVisible(true);
        String DateOrder = "";
        int gia = 0;
        int soluong=0;
        String TKH = "";
        String Diachi = "";
        ComboxKind.setSelectedIndex(0);
        int SĐT = 0;
        int MaHD = 0;
       try {
        TKH = txtTKH.getText(); // Lấy tên khách hàng từ ô văn bản
        Diachi = txtDiachi.getText(); // Lấy địa chỉ từ ô văn bản
        SĐT = Integer.parseInt(txtSĐT.getText()); // Lấy số điện thoại từ ô văn bản
        soluong=Integer.parseInt(txtSolg.getText());
        gia=Integer.parseInt(txtGia.getText());
        gia=soluong*gia;

        DateOrder = txtDateOrder.getText();
        Hoadon hd = new Hoadon(MaHD, TKH, SĐT, Diachi, DateOrder, gia);
        new DAOhd().AddHD(hd);
        showTableHD();
        ServerConnection.sendspInfoToServer(hd);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Đặt hàng không thành công! Vui lòng kiểm tra thông tin nhập vào.");
            e.printStackTrace(); // You can remove this line in production, it's for debugging purposes.
        }

       String Masp="";
        
        Masp=txtMasp.getText();
        soluong=Integer.parseInt(txtSolg.getText());
        gia=Integer.parseInt(txtGia.getText());
        int Gia=soluong*gia;
        SanphamCT sp=new SanphamCT(Masp, soluong, Gia);
        new DAOspCT().AddSP(sp);
        showTableSPCT();

//        banhang();
        showTableSP();
            } else {
                System.out.println("Khong du so luong de ban.");
            }
        } else {
            System.out.println("Ma san pham khong duoc tim thay.");
        }
    } else {
        System.out.println("Khong tim thay san pham hien tai.");

    }
}


    private void txtSĐTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSĐTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSĐTActionPerformed

    private void txtTKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTKHActionPerformed

    private void ChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChonActionPerformed

        Chon.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String date=((JTextField)jDate.getDateEditor().getUiComponent()).getText();
                txtDateOrder.setText(date);
            }
        });

        // TODO add your handling code here:
    }//GEN-LAST:event_ChonActionPerformed

    private void txtDateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOrderActionPerformed

    private void TableHoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableHoadonMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TableHoadonMouseClicked

    private void txtSolgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSolgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSolgActionPerformed

    private void ComboxKindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboxKindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboxKindActionPerformed

    private void banghdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banghdActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_banghdActionPerformed

    private void banghdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banghdMouseClicked
        jScrollPane3.setVisible(true);
        jScrollPane2.setVisible(false); 
        tong.setVisible(true);
        jPanel1.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_banghdMouseClicked

    private void bangctspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangctspMouseClicked
        jScrollPane3.setVisible(false);
        jScrollPane2.setVisible(true);
        tong.setVisible(false);
         jPanel1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_bangctspMouseClicked

    private void bangctspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangctspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bangctspActionPerformed

    private void menubarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubarMouseClicked
        openMenuBar();  
        menubar.setVisible(false);
        close.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menubarMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        closeMenuBar();  
        menubar.setVisible(true);
        close.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_closeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDiachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiachiActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int confirmed = JOptionPane.showConfirmDialog(null, 
            "Bạn muốn đăng xuất?", "Xác nhận đăng xuất",            
            JOptionPane.YES_NO_OPTION);
        System.out.println("Client da thoat khoi trang.");

        // Kiểm tra phản hồi của người dùng
        if (confirmed == JOptionPane.YES_OPTION) {
            // Người dùng chọn 'Yes', thực hiện đăng xuất
            start st = new start();
            st.setVisible(true); 
            dispose();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnaddspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddspMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddspMouseClicked

    private void addmspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addmspActionPerformed

    private void addtspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtspActionPerformed

    private void addlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addlActionPerformed

    private void addslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addslActionPerformed

    private void addgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addgActionPerformed

    private void addhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addhaActionPerformed

    private void btnxoaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaspActionPerformed
        selectedIndex=TableSP.getSelectedRow();
        int confirmationResult=JOptionPane.showConfirmDialog(this,"Bạn có chắc muốn xoá!");
        sanpham sp =Sanpham.get(selectedIndex);
        if(confirmationResult==JOptionPane.YES_OPTION) { 
        ServerConnection.sendDeletedspToServer(sp);
        new DAOsp().DeleteSP(sp.getID());
        showTableSP();   
        }
       
// TODO add your handling code here:
    }//GEN-LAST:event_btnxoaspActionPerformed

    private void btnupdateslgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateslgActionPerformed
        // TODO add your handling code here:
        int selectedIndex = TableSP.getSelectedRow();
    if (selectedIndex != -1) {
        String masp = TableSP.getValueAt(selectedIndex, 1).toString(); // Lấy mã sản phẩm từ hàng được chọn
        String newQuantityStr = JOptionPane.showInputDialog(this, "Nhập số lượng mới:");
        if (newQuantityStr != null && !newQuantityStr.isEmpty()) {
            try {
                int newQuantity = Integer.parseInt(newQuantityStr);
                if (newQuantity >= 0) {
                    DAOsp dao = new DAOsp(); // Tạo đối tượng DAOsp
                    dao.update1SPQuantity(masp, newQuantity); // Cập nhật số lượng vào cơ sở dữ liệu
                    JOptionPane.showMessageDialog(this, "Cập nhật số lượng thành công!");
                    showTableSP(); // Cập nhật lại bảng sau khi đã cập nhật dữ liệu
                    // Cập nhật lại số lượng trên bảng
                    TableSP.setValueAt(newQuantity, selectedIndex, 4); // Giả sử cột số lượng là cột thứ 5 (index 4)
                } else {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng là số nguyên dương.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng là số nguyên dương.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một hàng để cập nhật số lượng.");
    }
    }//GEN-LAST:event_btnupdateslgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Capnhatdonhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Capnhatdonhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Capnhatdonhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Capnhatdonhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Capnhatdonhang().setVisible(true);
          
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Chon;
    private javax.swing.JComboBox<String> ComboxKind;
    private javax.swing.JTable TableHoadon;
    private javax.swing.JTable TableSP;
    private javax.swing.JTable TableSPCT;
    private javax.swing.JTextField addg;
    private javax.swing.JTextField addha;
    private javax.swing.JTextField addl;
    private javax.swing.JTextField addmsp;
    private javax.swing.JTextField addsl;
    private javax.swing.JTextField addstt;
    private javax.swing.JTextField addtsp;
    private javax.swing.JButton bangctsp;
    private javax.swing.JButton banghd;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnaddsp;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdateslg;
    private javax.swing.JButton btnxoasp;
    private javax.swing.JLabel close;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel menubar;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JLabel tong;
    private javax.swing.JTextField txtDateOrder;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMasp;
    private javax.swing.JTextField txtSolg;
    private javax.swing.JTextField txtSĐT;
    private javax.swing.JTextField txtTKH;
    private javax.swing.JTextField txtTensp;
    // End of variables declaration//GEN-END:variables

    private void showTableHD() {
        hoadon = new DAOhd().getListHD();
        ModelHD.setRowCount(0);
        for (Hoadon hd:hoadon) {
            ModelHD.addRow(new Object[]{
                TableHoadon.getRowCount()+1,hd.getTKH(),hd.getSĐT(),hd.getDiachi(),hd.getDateOrder(),hd.getThanhtien()
            });
        }
    }   

    private void Tong() {
        int sum = 0;
        int rowCount = TableHoadon.getRowCount();
        int columnIndex = 5; // Cột thứ 6 (chỉ số bắt đầu từ 0)

        for (int i = 0; i < rowCount; i++) {
            Object value = TableHoadon.getValueAt(i, columnIndex);
            if (value != null) {
                try {
                    sum += Integer.parseInt(value.toString());
                    
                } catch (NumberFormatException ex) {
                    // Xử lý lỗi nếu giá trị không phải là số nguyên
                    System.out.println("Gia tri khong hop le o don thu " + (i + 1));
                }
            }
        }
        
        // Hiển thị tổng
        tong.setText("Tổng doanh thu: " + sum + " VNĐ");
    }

    private void showTableSP() {
       Sanpham=new DAOsp().getListSP();
       ModelSP.setRowCount(0);
       for(sanpham s:Sanpham) {
           ModelSP.addRow(new Object[]{
               TableSP.getRowCount()+1,s.getMasp(),s.getTensp(),s.getLoai(),s.getSoluong(),s.getGia(),s.getHinhAnh()
           });
       }
    }

    private void showTableSPCT() {
        sanphamct=new DAOspCT().getListSPCT();
        ModelSPCT.setRowCount(0);
        for (SanphamCT sp:sanphamct) {
            ModelSPCT.addRow(new Object[]{
            TableSPCT.getRowCount()+1,sp.getMasp(),sp.getSoluong(),sp.getGia()
        });
        }
    }
}